language: generic

services:
  - docker



deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY

    secret_access_key: $SECRET_KEY

    region: "ap-south-1"
    app: "myappeb"
    env: "Myappeb-env"
    bucket_name: "myappb1"
    bucket_path: docker

    on:
      branch: branch1

